{{- if and (not .Values.existingSecret) .Values.agentToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesecure-agent.fullname" . }}
  labels:
    {{- include "kubesecure-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretKey }}: {{ .Values.agentToken | b64enc | quote }}
{{- end }}
